Makes all JS tests run under node.
Adds a command-line runner for grace code: js/tests/grace-node.

This involves quite extensive changes to the way that global
variables and global constants are declared, with the declarations
of the variables moving from gracelib.js to grace-node (for the
command line) and minigrace.in.js (for the browser).  Also adds
a makefile target (test.js) for running the tests at the command line.

Adds some new tests, and moves two known-failing tests to a
subdirectory.

diff --git a/tests/harness b/tests/harness
--- a/tests/harness
+++ b/tests/harness
@@ -4,10 +4,11 @@ set -e
 
 if [ $# -lt 3 ]
 then
-    echo "Error: harness requires three arguments" >&2
-    echo "- Grace command" >&2
-    echo "- Directory of tests to run" >&2
-    echo "- Command to execute compiled code (empty for native)" >&2
+    echo "Error: harness requires three or more arguments" >&2
+    echo "- compilation command" >&2
+    echo "- directory containing tests" >&2
+    echo "- command to execute compiled code (empty for native)" >&2
+    echo '- <test file name prefix>*  ; if omitted, all tests in directory'
 fi
 GRACE="$1"
 TESTDIR="$2"
