Add -a automatic-install mode to tarball-bootstrap

diff --git a/tools/tarball-bootstrap b/tools/tarball-bootstrap
--- a/tools/tarball-bootstrap
+++ b/tools/tarball-bootstrap
@@ -8,7 +8,29 @@ die() {
 
 TARBALL=$1
 
-if ! [ "$TARBALL" ]
+if [ "$TARBALL" = "-a" ]
+then
+    pushd "$(git rev-parse --show-toplevel)" >/dev/null
+    rev=$(awk -F= '/STABLE=/ { print $2 }' Makefile)
+    ver=$(tools/calculate-version $rev)
+    url=http://ecs.vuw.ac.nz/~mwh/minigrace/dist/minigrace-$ver.tar.bz2
+    echo Will fetch tarball from $url...
+    if wget --version >/dev/null 2>&1
+    then
+        wget "$url" || die "Error fetching file. Download manually and re-run script."
+    elif curl --version >/dev/null 2>&1
+    then
+        curl -L -O "$url" || die "Error fetching file. Download manually and re-run script."
+    else
+        die "Neither wget nor curl were found. Unable to retrieve file automatically. Download manually and re-run script."
+    fi
+    echo "Download complete. Will compile now..."
+    "$0" "minigrace-$ver.tar.bz2" || die "Failed to build. See above for details."
+    rm -f minigrace-$ver.tar.bz2
+    popd >/dev/null
+    echo Done
+    exit 0
+elif ! [ "$TARBALL" ]
 then
     echo "Usage: $0 <tarball>"
     echo "Compiles <tarball> and installs it as known-good bootstrap version."
@@ -16,6 +38,7 @@ then
     echo "Download the tarball of a past bootstrap version and pass it to"
     echo "this script as <tarball> to install it for bootstrapping. Afterwards"
     echo "\`make\` will build the latest version from the source repository."
+    echo "You can also run \`$0 -a\` to download and install automatically."
     echo
     cd "$(git rev-parse --show-toplevel)"
     rev=$(awk -F= '/STABLE=/ { print $2 }' Makefile)
@@ -39,10 +62,19 @@ tar xjvf "$TARBALL" || die "Failed to extract tarball"
 dir=$(sed 's/.tar.bz2//' < <(basename "$TARBALL"))
 pushd "$dir"
 ./configure || die "Failed to configure tarball"
-sed -i "" 's/-std=c99//' Makefile
 make || die "Failed to build"
 hash=$(./minigrace --version | awk '/git revision/ { print $3 }')
 kgdir=../known-good/$(uname -s)-$(uname -m)/$hash
+if [ -e "$kgdir" ]
+then
+    echo
+    echo "Known-good version $hash is already installed"
+    echo "If you want to re-build it, delete the directory:"
+    echo "    $(readlink -f "$kgdir")"
+    popd >/dev/null
+    rm -rf "$dir"
+    exit 0
+fi
 mkdir -p "$kgdir"
 for f in gracelib.h gracelib.o minigrace unicode.gso unicode.gcn mirrors.gso repl.gso mirrors.gcn repl.gcn
 do
