Updates to recommend bootstrap from tarball

diff --git a/tools/tarball-bootstrap b/tools/tarball-bootstrap
--- a/tools/tarball-bootstrap
+++ b/tools/tarball-bootstrap
@@ -16,6 +16,13 @@ then
     rev=$(awk -F= '/STABLE=/ { print $2 }' Makefile)
     gen=$(tools/git-calculate-generation "$rev")
     ver=$(git show --format=%B $rev:util.grace | sed -n 's/var versionNumber := "\([^"]\+\)"/\1/p')
+    if ! [ "$ver" ]
+    then
+        echo "The newest bootstrap tarball could not be calculated on your"
+        echo "system, but a working tarball should be available from:"
+        echo "   http://ecs.vuw.ac.nz/~mwh/minigrace/dist/minigrace-0.0.7.1033.tar.bz2"
+        exit 0
+    fi
     echo "The tarball for the newest bootstrapping version should be called:"
     echo "   minigrace-$ver.$gen.tar.bz2"
     echo "and should be available from:"
