Switch stable to a C-default version

diff --git a/known-good/Makefile b/known-good/Makefile
--- a/known-good/Makefile
+++ b/known-good/Makefile
@@ -111,5 +111,28 @@ $(ARCH)/minigrace-f26b7f1f999067bfa44608cb282e26c28b49eaf8: $(ARCH)/minigrace-00
 	rm -f compiler.gc gracelib.c
 	rm -f unicode.gso unicode.c unicodedata.h unicode.gco
 
+$(ARCH)/minigrace-4df500fa93a8e8f5886b3590424a7aa67e21bf0e:
+	tar xzvf ./independent/c-4df500fa93a8e8f5886b3590424a7aa67e21bf0e.tar.gz
+	cd c-4df500fa93a8e8f5886b3590424a7aa67e21bf0e && \
+	if [ "$$GNU_MAKE" ] ; \
+	then \
+	    $$GNU_MAKE ; \
+	elif make -v 2>&1 | grep -q GNU ; \
+	then \
+	    make ; \
+	elif gmake -v 2>&1 | grep -q GNU ; \
+	then \
+	    gmake ; \
+	else \
+	    echo "Could not find GNU make." ; \
+	    echo "Set GNU_MAKE to the correct path and try again." ; \
+	    exit 1 ; \
+	fi
+	mkdir -p "$(ARCH)"
+	mv c-4df500fa93a8e8f5886b3590424a7aa67e21bf0e/minigrace $(ARCH)/minigrace-4df500fa93a8e8f5886b3590424a7aa67e21bf0e
+	cp c-4df500fa93a8e8f5886b3590424a7aa67e21bf0e/gracelib.o $(ARCH)/gracelib-4df500fa93a8e8f5886b3590424a7aa67e21bf0e.o
+	cp c-4df500fa93a8e8f5886b3590424a7aa67e21bf0e/gracelib.h $(ARCH)/gracelib-4df500fa93a8e8f5886b3590424a7aa67e21bf0e.h
+	rm -rf c-4df500fa93a8e8f5886b3590424a7aa67e21bf0e
+
 $(ARCH)/minigrace-%:
 	./make-known-good $* $(ARCH)
